jjrecs/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^productviews/', include('productviews.urls', namespace="productviews")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url('^accounts/', include('django.contrib.auth.urls', namespace="auth"))
]

productviews/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /
    url(r'^$', views.view_list, name='view_list'),
    # ex: /product/
    url(r'^product$', views.product_list, name='product_list'),
    # ex: /product/357/
    url(r'^product/(?P<product_id>[0-9]+)/$', views.product_detail, name='product_detail'),
    # ex: /view/user - get views for the logged user
    url(r'^view/user/(?P<username>\w+)/$', views.user_view_list, name='user_view_list'),
    url(r'^view/user/$', views.user_view_list, name='user_view_list'),
    # ex: /recommendation - get recommendations for the logged user
    # url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),
    url(r'^recommendation/user/(?P<username>\w+)/$', views.user_recommendation_list, name='user_recommendation_list'),
    url(r'^recommendation/user/$', views.user_recommendation_list, name='user_recommendation_list'),
]

productviews/models.py
from django.db import models
import numpy as np


class Product(models.Model):
    name = models.CharField(max_length=200)
    
    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.view_set.all())
        return np.sum(all_ratings)
        
    def __unicode__(self):
        return self.name


class View(models.Model):
    product = models.ForeignKey(Product)
    pub_date = models.DateTimeField('date viewed')
    user_name = models.CharField(max_length=100)
    rating = models.IntegerField(default=1)

productviews/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from .models import View, Product
from .suggestions import update_recs, run_user_recs

def view_list(request):
    latest_view_list = View.objects.order_by('-pub_date')[:9]
    context = {'latest_view_list':latest_view_list}
    return render(request, 'productviews/view_list.html', context)


def product_list(request):
    product_list = Product.objects.order_by('-name')
    context = {'product_list':product_list}
    return render(request, 'productviews/product_list.html', context)


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'productviews/product_detail.html', {'product': product})
    
def user_view_list(request, username=None):
    if not username:
        username = request.user.username
    latest_view_list = View.objects.filter(user_name=username).order_by('-pub_date')
    context = {'latest_view_list':latest_view_list, 'username':username}
    return render(request, 'productviews/user_view_list.html', context)
    
@login_required
def user_recommendation_list(request, username=None):
    if not username:
        username = request.user.username
    # get this user views
    user_views = View.objects.filter(user_name=username).prefetch_related('product')
    # from the views, get a set of product IDs
    user_views_product_ids = set(map(lambda x: x.product.id, user_views))
    
    try:
        user_name_current = \
            User.objects.get(username=request.user.username).id
        run_user_recs()
    except: # if no user
        update_recs()
        user_name_current = \
            User.objects.get(username=request.user.username).id
    
    # then get a product list excluding the previous IDs
    product_list = Product.objects.exclude(id__in=user_views_product_ids)

    return render(
        request, 
        'productviews/user_recommendation_list.html', 
        {'username': username,'product_list': product_list}
    )

productviews/templates/productviews/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav  class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'productviews:view_list' %}">Johnson and Johnson</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'productviews:product_list' %}">Product List</a></li>
                <li><a href="{% url 'productviews:view_list' %}">Home</a></li>
            </ul>
        </div>
    </nav>
    

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}

productviews/templates/productviews/product_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>{{ product.name }}</h2>
<h5>{{ product.view_set.count }} views</h5>
{% endblock %}

{% block content %}
<h3>Recent views</h3>

{% if product.view_set.all %}
<div class="row">
    {% for view in product.view_set.all %}
    <div class="col-xs-6 col-lg-4">
        <h6>Viewed {{ view.rating }} time(s) by <a href="{% url 'productviews:user_view_list' view.user_name %}"><b>{{ view.user_name }}</b></a> </h6>
		<h6>at {{view.pub_date}}</h6>
		<h6>id: <i>{{view.id}}</i></h6>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No views for this product yet</p>
{% endif %}
{% endblock %}

productviews/templates/productviews/product_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Product List</h2>
{% endblock %}

{% block content %}
{% if product_list %}
<div class="row">
    {% for product in product_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'productviews:product_detail' product.id %}">
        {{ product.name }}
        </a></h4>
        <h5>{{ product.view_set.count }} views</h5>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No products are available.</p>
{% endif %}
{% endblock %}

productviews/templates/productviews/user_recommendation_list.html
{% extends 'productviews/product_list.html' %}

{% block title %}
<h2>Product suggestions for {{ username }}</h2>
{% endblock %}

productviews/templates/productviews/user_view_list.html
{% extends 'productviews/view_list.html' %}

{% block title %}
<h2>Views by {{ username }}</h2>
{% endblock %}

productviews/templates/productviews/view_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Latest views</h2>
{% endblock %}

{% block content %}
{% if latest_view_list %}
<div class="row">
    {% for view in latest_view_list %}
    <div class="col-xs-6 col-lg-4">
        <h4>{{ view.product.name }}        </h4>
        <h6>Viewed: {{ view.rating }} time(s) by <a href="{% url 'productviews:user_view_list' view.user_name %}">{{ view.user_name }}</a></h6>
		<h6>at {{ view.pub_date }}</h6>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No views are available.</p>
{% endif %}
{% endblock %}

templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'productviews:view_list' %}">Johnson and Johnson</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'productviews:product_list' %}">Product List</a></li>
                <li><a href="{% url 'productviews:view_list' %}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'productviews:user_view_list' user.username %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'productviews:user_recommendation_list' %}">Product suggestions</a></li>
                <li><a href="{% url 'auth:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'auth:login' %}">Login</a></li>
				<li><a href="/accounts/register">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}